# Generated by Django 4.2.4 on 2024-09-09 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0002_rename_status_leave_leave_approved_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leave',
            name='leave_approved_status',
        ),
    ]
