# Generated by Django 4.2.4 on 2024-09-09 20:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0003_remove_leave_leave_approved_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='entry_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='leave',
            name='leave_type',
            field=models.CharField(choices=[('Sick', 'Sick'), ('Casual', 'Casual'), ('NPL', 'Non-Paid Leave')], max_length=10),
        ),
    ]
