# Generated by Django 4.2.4 on 2024-09-09 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0004_leave_entry_date_alter_leave_leave_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave',
            name='entry_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
