# Generated by Django 4.2.4 on 2024-08-23 17:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('power_user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StandardUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_no', models.CharField(max_length=11)),
                ('supervisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supervisor_power_user', to='power_user.poweruser')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='standard_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
