# Generated by Django 4.2.4 on 2024-08-25 08:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee', '0004_alter_employee_employee_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobProfileHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('Confirmation', 'Confirmation'), ('Promotion', 'Promotion'), ('Separation', 'Separation'), ('Transfer', 'Transfer')], max_length=50)),
                ('details', models.TextField()),
                ('event_date', models.DateField()),
                ('entry_date', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.employee')),
            ],
        ),
    ]
