# Generated by Django 4.2.4 on 2024-08-25 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_profile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobprofilehistory',
            name='event_type',
            field=models.CharField(choices=[('Joining', 'Joining'), ('Confirmation', 'Confirmation'), ('Promotion', 'Promotion'), ('Separation', 'Separation'), ('Transfer', 'Transfer')], max_length=50),
        ),
    ]
