# Generated by Django 4.2.4 on 2024-08-26 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_profile', '0003_rename_event_date_jobprofilehistory_effective_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobprofilehistory',
            name='event_type',
            field=models.CharField(choices=[('Joining', 'Joining'), ('Confirmation', 'Confirmation'), ('Promotion', 'Promotion'), ('Separation', 'Separation'), ('Training', 'Training'), ('Transfer', 'Transfer'), ('Transfer_Withdraw', 'Transfer_Withdraw')], max_length=50),
        ),
    ]
