# Generated by Django 4.2.4 on 2024-08-23 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('admin', 'Admin'), ('power_user', 'Power_user'), ('standard_user', 'Standard_user'), ('viewer', 'Viewer')], default='viewer', max_length=20),
        ),
    ]
