# Generated by Django 4.2.4 on 2024-08-25 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee', '0004_alter_employee_employee_id'),
        ('employment', '0009_alter_employmentinfo_probation_period_months_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransferInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transfer_effective_date', models.DateField()),
                ('entry_date', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.employee')),
                ('transfer_to_department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfer_to_department', to='employment.department')),
                ('transfer_to_location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfer_to_location', to='employment.joblocation')),
            ],
        ),
    ]
