# Generated by Django 4.2.4 on 2024-08-24 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employment', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personalinfo',
            old_name='smart_nid',
            new_name='smart_id',
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='blood_group',
            field=models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=3),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='educational_degree',
            field=models.CharField(choices=[('SSC', 'SSC'), ('HSC', 'HSC'), ('BBA', 'BBA'), ('BBS', 'BBS'), ('BA', 'BA'), ('MBA', 'MBA'), ('MSS', 'MSS'), ('MA', 'MA')], max_length=20),
        ),
    ]
