# Generated by Django 4.2.4 on 2024-08-24 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employment', '0002_rename_smart_nid_personalinfo_smart_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalinfo',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
    ]
