# Generated by Django 4.2.4 on 2024-08-24 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employment', '0004_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='Designation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='JobLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='educational_degree',
            field=models.CharField(choices=[('SSC', 'SSC'), ('Dakhil', 'Dakhil'), ('HSC', 'HSC'), ('Alim', 'Alim'), ('BBA', 'BBA'), ('BBS', 'BBS'), ('BA', 'BA'), ('BSc', 'BSc'), ('Fadil', 'Fadil'), ('MBA', 'MBA'), ('MSS', 'MSS'), ('MA', 'MA'), ('MSc', 'MSc'), ('Kamil', 'Kamil'), ('PostGraduate', 'PostGraduate')], max_length=20),
        ),
    ]
