# Generated by Django 4.2.4 on 2024-08-24 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_alter_employee_employee_id'),
        ('employment', '0005_designation_joblocation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmploymentInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Suspended', 'Suspended')], default='Active', max_length=10)),
                ('joining_date', models.DateField()),
                ('probation_period_months', models.IntegerField(verbose_name=range(1, 12))),
                ('confirmation_effective_date', models.DateField(blank=True, null=True)),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='employment.department')),
                ('designation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='employment.designation')),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='employee.employee')),
                ('job_location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='employment.joblocation')),
            ],
        ),
    ]
