# Generated by Django 4.2.4 on 2024-08-24 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employment', '0006_employmentinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employmentinfo',
            name='probation_period_months',
            field=models.IntegerField(choices=[(3, 3), (6, 6)], default=6),
        ),
    ]
