# Generated by Django 4.2.4 on 2024-08-25 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employment', '0008_alter_employmentinfo_probation_period_months'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employmentinfo',
            name='probation_period_months',
            field=models.IntegerField(choices=[(1, 1), (3, 3), (6, 6)], default=6),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='educational_degree',
            field=models.CharField(choices=[('SSC', 'SSC'), ('Dakhil', 'Dakhil'), ('HSC', 'HSC'), ('Alim', 'Alim'), ('BBA', 'BBA'), ('BBS', 'BBS'), ('BSS', 'BSS'), ('BA', 'BA'), ('BSc', 'BSc'), ('Fadil', 'Fadil'), ('MBA', 'MBA'), ('MBS', 'MBS'), ('MSS', 'MSS'), ('MA', 'MA'), ('MSc', 'MSc'), ('Kamil', 'Kamil'), ('PostGraduate', 'PostGraduate')], max_length=20),
        ),
    ]
