# Generated by Django 4.2.4 on 2024-08-25 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employment', '0009_alter_employmentinfo_probation_period_months_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalinfo',
            name='email',
            field=models.EmailField(default='sayed91515@gmail.com', max_length=100),
        ),
    ]
