# Generated by Django 4.2.4 on 2024-08-26 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employment', '0010_alter_personalinfo_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='employmentinfo',
            name='is_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
