# Generated by Django 4.2.4 on 2024-08-27 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employment', '0011_employmentinfo_is_confirmed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalinfo',
            name='email',
            field=models.EmailField(max_length=100),
        ),
    ]
