# Generated by Django 4.2.4 on 2024-08-27 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('promotion', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='promotioninfo',
            old_name='promoted_from_grade',
            new_name='promoted_salary_grade',
        ),
        migrations.RenameField(
            model_name='promotioninfo',
            old_name='promoted_from_step',
            new_name='promoted_salary_step',
        ),
        migrations.RemoveField(
            model_name='promotioninfo',
            name='promoted_from_designation',
        ),
        migrations.RemoveField(
            model_name='promotioninfo',
            name='promoted_to_grade',
        ),
        migrations.RemoveField(
            model_name='promotioninfo',
            name='promoted_to_step',
        ),
    ]
