# Generated by Django 4.2.4 on 2024-08-27 18:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('promotion', '0002_rename_promoted_from_grade_promotioninfo_promoted_salary_grade_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotioninfo',
            name='entry_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
