# Generated by Django 4.2.4 on 2024-08-26 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salary', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salaryinfo',
            old_name='step',
            new_name='salary_step',
        ),
    ]
