# Generated by Django 4.2.4 on 2024-09-09 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salary', '0003_salaryinfo_casual_leave_balance_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salaryinfo',
            old_name='salary_deduction_npl',
            new_name='npl_salary_deduction',
        ),
    ]
