# Generated by Django 4.2.4 on 2024-09-10 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salary', '0004_rename_salary_deduction_npl_salaryinfo_npl_salary_deduction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salaryinfo',
            name='npl_salary_deduction',
        ),
    ]
