# Generated by Django 4.2.4 on 2024-09-09 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0003_alter_payroll_consolidated_salary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payroll',
            name='status',
            field=models.CharField(default='Active', max_length=10),
        ),
    ]
