# Generated by Django 4.2.4 on 2024-09-10 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0004_payroll_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payroll',
            old_name='npl_deduction',
            new_name='npl_salary_deduction',
        ),
    ]
