# Generated by Django 4.2.4 on 2024-09-10 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0006_alter_payroll_net_salary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payroll',
            name='net_salary',
        ),
        migrations.RemoveField(
            model_name='payroll',
            name='npl_salary_deduction',
        ),
    ]
