# Generated by Django 4.2.4 on 2024-09-10 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0007_remove_payroll_net_salary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payroll',
            name='net_salary',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='payroll',
            name='npl_salary_deduction',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
