# Generated by Django 4.2.4 on 2024-10-18 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0009_alter_payroll_options_payroll_late_joining_deduction_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payroll',
            options={'ordering': ['-month', 'employee_id'], 'verbose_name': 'Payroll', 'verbose_name_plural': 'Payrolls'},
        ),
    ]
