# Generated by Django 4.2.4 on 2024-08-27 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee', '0004_alter_employee_employee_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeparationInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cause_of_separation', models.CharField(choices=[('Family problem', 'Family problem'), ('Personal problem', 'Personal problem'), ('Better opportunity', 'Better opportunity'), ('Corruption', 'Corruption'), ('Unauthorized absence', 'Unauthorized absence')], max_length=50)),
                ('application_submission_date', models.DateField()),
                ('separation_effect_date', models.DateField()),
                ('entry_date', models.DateTimeField(auto_now_add=True)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='employee.employee')),
            ],
        ),
    ]
